### ISSUE TITLE
Colorize `_MESSAGE` text

### ISSUE THREAD

**Issue by BlackstoneEngineering** [ARMmbed/greentea#166] opened 2016-07-13 21:41 UTC
## Problem

Using the `TEST_ASSERT_MESSAGE( fn ,"message goes here")` is very useful for explaining why a test failed and guiding the developers to fix the issue. In ther current setup though this potentially very useful text is hidden behind the `-v` flag and lost among a hundred other lines of near identical text.
## Solution
- add colorization / bolding to the text
- Consider moving these messages out from behind the `-v` flag to be a first class citizen

**Comment by ciarmcom** [comment] 2016-07-14 00:26
ARM Internal Ref: IOTSFW-2791

**Comment by theotherjimmy** [comment] 2017-09-20 16:54
Duplicate of #191

**Closed by theotherjimmy** 2017-09-20 16:54 UTC
Labels: enhancement, mirrored
