### ISSUE TITLE
Provide a mechanism to change baud rate

### ISSUE THREAD

**Issue by bremoran** [ARMmbed/greentea#162] opened 2016-07-07 12:12 UTC
In some tests, it is desirable to change baud rates. It would be nice if mbedgt (or one of its subtools) and greentea-client were to provide a mechanism for this. When a baud rate change is initiated, it is likely necessary for mbedgt to close the serial port, reopen with the new parameters, then initiate a new sync.

cc @PrzemekWirkus

**Comment by ciarmcom** [comment] 2016-07-07 12:29
ARM Internal Ref: IOTSFW-2774

**Comment by PrzemekWirkus** [comment] 2016-07-07 23:16
This feature will require us to change a bit `htrun` and `greentea-client`. We will have to provide inetrface (events) to change baudrate and handshake after reconnection.
Main changes may include:
* Add new event to baudrate exchange from DUT, in `greentea-client`
* Add handle for event "request to change baudrate", in `htrun`
  * Note: this event would be available for all host tests inherited from base host test class
  * Generic API should be provided on `htrun` / host test side
* No dependency on `mbed-os` or other, so each OS should use its own way to handshake after reconnection.

**Comment by bridadan** [comment] 2017-06-06 18:48
This is a duplicate of #196. @adbridge @mazimkhan Can we please close this one?

**Closed** 2017-06-07 10:02 UTC
Labels: enhancement, mirrored
